 # Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
  production:		  production:
 -  url: redis://localhost:6379/1		 +  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
  		  
  development:		  development:
    url: redis://localhost:6379/2		    url: redis://localhost:6379/2
